
from flask import Flask, Blueprint, render_template, request, abort
from ai_class import ai_class

# Create a Blueprint with /nornnet as the URL prefix
# To run locally: Uncomment the first one, Comment the second one
nornnet_bp = Blueprint('nornnet', __name__, url_prefix='/    ', template_folder='templates')
# nornnet_bp = Blueprint('nornnet', __name__, url_prefix='/nornnet    ', template_folder='templates')

# Get post is for the user input and ai response
@nornnet_bp.route("/", methods=["GET", "POST"])
def hello():
    # set up the input variables for the user and ai
    user_input = ""
    ai_response = ""

    # Set up the ai class
    robot = ai_class()

    if request.method == "Post":
        user_input = request.form["user_input"]
        robot.set_user_question(user_input)
        ai_response = robot.get_ai_response()

    return render_template("index.html", user_input=user_input, ai_response=ai_response)



@nornnet_bp.route('/docs')
def docs():
    return render_template('docs.html')


# Create the Flask app and serve static files under the /cs prefix so
# requests like /cs/static/css/styles.css are handled by Flask.
# This ensures the stylesheet link generated by url_for('static', ...) is
# reachable when the app's routes are under the /nornnet blueprint prefix.
app = Flask(__name__, static_folder='static', static_url_path='/nornnet/static')

# Register the blueprint
app.register_blueprint(nornnet_bp)


@app.context_processor
def inject_globals():
    # Provide the current year to templates for footer
    from datetime import datetime
    return dict(current_year=datetime.utcnow().year)


if __name__ == "__main__":
    app.run(debug=True)
